### ISSUE TITLE
Wallet Connect Image Changed

### ISSUE THREAD

**Issue by osterby** [silviopaganini/nft-market#23]
Wallet Connect must have removed the asset you used. I found it on their github though. Happy to put in a pull request if you're open to that.

https://raw.githubusercontent.com/WalletConnect/walletconnect-assets/b9644035864fb4b6d6ed55e0f67ad302377bd6f1/svg/original/walletconnect-logo.svg

**Comment by silviopaganini** [comment]
oh nice one! happy to merge your PR when you have it!

**Comment by osterby** [comment]
I gave it a go, but got permission denied messages.

**Comment by osterby** [comment]
Did you expect a fork and merge?

**Comment by silviopaganini** [comment]
oh, you need to fork it first, then pull request
