### ISSUE TITLE
getting started

### ISSUE THREAD

**Issue by test2a** [silviopaganini/nft-market#25]
i found your repo and i have some questions. 

1. how much of a vps do i need to set this up in terms of specs?
2. my current understanding from looking at the readme is that this "repo" sets up a front-end for opensea or is it that one can build one completely independent
3.  have you used this in production or it is limited to only testnet?
4.

**Comment by silviopaganini** [comment]
1. VPS?
2. You can build your own based on this, just follow the Readme instructions for the other repos
3. not used in production, just parts of it
