### ISSUE TITLE
NFTs Not Rendering in Marketplace

### ISSUE THREAD

**Issue by bn185068** [silviopaganini/nft-market#5]
@silviopaganini love the marketplace! Would like to use it but can't seem to get the NFTs to render. Can you help me out with what I may be missing?

![image](https://user-images.githubusercontent.com/66647580/122462580-c7d11a80-cf82-11eb-9768-6aa398d2f2d5.png)

**Comment by sj185222** [comment]
@silviopaganini I'm facing the same issue! Installed the two dependancies aswell

**Comment by silviopaganini** [comment]
damn, no need to panic, there was a problem minting the test tokens on Rinkeby yesterday due to some maintenance
on IPFS, the tokens up to 60 are lost

**Comment by bn185068** [comment]
@silviopaganini thanks for the response. We've been able to diagnose some our other problems as well, and we have the marketplace working. Thanks! 

If we wanted to use a non-metamask wallet and not leverage OpenSea, how might we go about doing so?
